---
- name: Desplegar máquina virtual con Snort
  hosts: localhost
  gather_facts: false

  vars:
    vm_name: "ubuntu-cloud-init-vm"
    vm_id: 105
    vm_memory: 4096
    vm_cores: 2
    vm_ip: "192.168.100.10"
    vm_gateway: "192.168.100.3"
    cloud_init_user: "carlos"
    cloud_init_password: "carlos"
    image_path: "/var/lib/vz/template/iso/jammy-server-cloudimg-amd64.img"
    storage: "local-lvm"

  tasks:
    - name: Verificar si la imagen existe
      stat:
        path: "{{ image_path }}"
      register: image_stat

    - name: Crear la VM si no existe
      community.general.proxmox_kvm:
        api_host: 192.168.100.3
        api_user: root@pam
        api_password: carlos1234
        node: proxmox
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        memory: "{{ vm_memory }}"
        cores: "{{ vm_cores }}"
        ostype: l26
        net:
          net0: "model=virtio,bridge=vmbr0"
        scsihw: virtio-scsi-pci
               bootdisk: scsi0
        storage: "{{ storage }}"
        state: present
      delegate_to: proxmox

    - name: Importar el disco a la VM
      command: qm importdisk {{ vm_id }} {{ image_path }} {{ storage }}
      when: not image_stat.stat.exists
      delegate_to: proxmox

    - name: Adjuntar el disco a la VM en Proxmox
      community.general.proxmox_kvm:
        api_host: 192.168.100.3
        api_user: root@pam
        api_password: carlos1234
        node: proxmox
        vmid: "{{ vm_id }}"
        scsi:
          scsi0: "local-lvm:20,format=qcow2"
        state: present
      delegate_to: proxmox

    - name: Agregar consola serial a la VM
      command: qm set {{ vm_id }} --serial0 socket
      delegate_to: proxmox

    - name: Agregar adaptador VGA para noVNC
      command: qm set {{ vm_id }} --vga std
      delegate_to: proxmox

    - name: Deshabilitar KVM en la VM
      command: qm set {{ vm_id }} --kvm 0
      delegate_to: proxmox

    - name: Generar archivo cloud-init personalizado
      template:
        src: ../cloud_init/snort-user-data.yml.j2
              dest: /var/lib/vz/snippets/{{ vm_name }}-user-data.yml
      delegate_to: proxmox

    - name: Crear el disco de cloud-init
      command: qm set {{ vm_id }} --ide2 {{ storage }}:cloudinit
      delegate_to: proxmox

    - name: Adjuntar archivo cloud-init personalizado
      command: qm set {{ vm_id }} --cicustom "user=local:snippets/{{ vm_name }}-user-data.yml"
      delegate_to: proxmox

    - name: Iniciar la VM
      community.general.proxmox_kvm:
        api_host: 192.168.100.3
        api_user: root@pam
        api_password: carlos1234
        node: proxmox
        vmid: "{{ vm_id }}"
        state: started
      delegate_to: proxmox

    - name: Esperar que la VM responda por SSH
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        delay: 15
        timeout: 600
        state: started

    - name: Instalar Snort en la VM
      ansible.builtin.apt:
        name: snort
        state: present
        update_cache: yes
      delegate_to: "{{ vm_ip }}"
      become: true

    - name: Reiniciar Snort
      ansible.builtin.service:
        name: snort
        state: restarted
      delegate_to: "{{ vm_ip }}"
      become: true
